/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._bms;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import dms.data.Sites;

public class _site__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_2.evalBoolean(_jsp_env)) {
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _caucho_expr_3.print(out, _jsp_env, false);
        out.write(_jsp_string4, 0, _jsp_string4.length);
      }
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_4.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
      _caucho_expr_5.print(out, _jsp_env, false);
      out.write(_jsp_string7, 0, _jsp_string7.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _caucho_expr_7.print(out, _jsp_env, false);
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _caucho_expr_8.print(out, _jsp_env, false);
      out.write(_jsp_string10, 0, _jsp_string10.length);
      _caucho_expr_9.print(out, _jsp_env, false);
      out.write(_jsp_string11, 0, _jsp_string11.length);
      _caucho_expr_10.print(out, _jsp_env, false);
      out.write(_jsp_string12, 0, _jsp_string12.length);
      _caucho_expr_11.print(out, _jsp_env, false);
      out.write(_jsp_string13, 0, _jsp_string13.length);
      _caucho_expr_12.print(out, _jsp_env, false);
      out.write(_jsp_string14, 0, _jsp_string14.length);
      _caucho_expr_13.print(out, _jsp_env, false);
      out.write(_jsp_string15, 0, _jsp_string15.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string16, 0, _jsp_string16.length);
      _caucho_expr_15.print(out, _jsp_env, false);
      out.write(_jsp_string17, 0, _jsp_string17.length);
      _caucho_expr_16.print(out, _jsp_env, false);
      out.write(_jsp_string18, 0, _jsp_string18.length);
      if (_caucho_expr_17.evalBoolean(_jsp_env)) {
        out.write(_jsp_string19, 0, _jsp_string19.length);
      }
      else {
        out.write(_jsp_string20, 0, _jsp_string20.length);
      }
      out.write(_jsp_string21, 0, _jsp_string21.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.id}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.siteName}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.picUrl!=null}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.picUrl}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.webPage}");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.address}");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.domain}");
    _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.onlineTime}");
    _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.purchaseType}");
    _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.siteType}");
    _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.frequency}");
    _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.averagePurchaser}");
    _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.email}");
    _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.qq}");
    _caucho_expr_14 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.msn}");
    _caucho_expr_15 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.phone}");
    _caucho_expr_16 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.brief}");
    _caucho_expr_17 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.viewFlag==1}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("bms/site.jsp"), -5460478257504222842L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;
  private static com.caucho.el.Expr _caucho_expr_14;
  private static com.caucho.el.Expr _caucho_expr_15;
  private static com.caucho.el.Expr _caucho_expr_16;
  private static com.caucho.el.Expr _caucho_expr_17;

  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string9;
  private final static char []_jsp_string12;
  private final static char []_jsp_string18;
  private final static char []_jsp_string21;
  private final static char []_jsp_string11;
  private final static char []_jsp_string17;
  private final static char []_jsp_string10;
  private final static char []_jsp_string0;
  private final static char []_jsp_string20;
  private final static char []_jsp_string4;
  private final static char []_jsp_string7;
  private final static char []_jsp_string13;
  private final static char []_jsp_string16;
  private final static char []_jsp_string19;
  private final static char []_jsp_string2;
  private final static char []_jsp_string8;
  private final static char []_jsp_string15;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string14;
  static {
    _jsp_string1 = "\"/>\r\n<table width=\"90%\" border=\"1\" align=\"center\" cellpadding=\"0\"\r\n	cellspacing=\"0\" bordercolorlight=#AAAAAA bordercolordark=white>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u7ad9\u70b9\u540d\u79f0\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"siteName\" value=\"".toCharArray();
    _jsp_string3 = "\r\n				<img src=\"".toCharArray();
    _jsp_string9 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u8d2d\u4e70\u7c7b\u578b\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"purchaseType\" value=\"".toCharArray();
    _jsp_string12 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u56e2\u8d2d\u5e73\u5747\u8d2d\u4e70\u4eba\u6570\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"averagePurchaser\" value=\"".toCharArray();
    _jsp_string18 = "</textarea>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			 \u662f\u5426\u663e\u793a\r\n		</td>\r\n		<td>\r\n			".toCharArray();
    _jsp_string21 = "\r\n		</td>\r\n	</tr>	\r\n</table>\r\n<p style=\"text-align:center\"><input type=\"submit\" name=\"submit1\" value=\"\u63d0\u4ea4\">&nbsp;&nbsp;<input type=\"reset\" name=\"reset1\" value=\"\u53d6\u6d88\">&nbsp;&nbsp;<input type=\"button\" name=\"back\" value=\"\u8fd4\u56de\" onclick=\"history.go(-1);\"></p>\r\n</form>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string11 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u56e2\u8d2d\u7ec4\u7ec7\u9891\u7387\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"frequency\" value=\"".toCharArray();
    _jsp_string17 = "\"/>\r\n		</td>\r\n	</tr>			<tr>\r\n		<td width=\"80\">\r\n			\u7b80\u8981\u63cf\u8ff0\r\n		</td>\r\n		<td>\r\n			<textarea name=\"brief\" rows=\"5\" cols=\"100\">".toCharArray();
    _jsp_string10 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u7f51\u7ad9\u7c7b\u578b\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"siteType\" value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\" />\r\n<meta name=\"description\" content=\" \">\r\n<meta name=\"keywords\" content=\" \">\r\n<title></title>\r\n</head>\r\n<body>\r\n<br>\r\n<form name=\"siteForm\" method=\"post\" action=\"site.do?method=edit&domain=\u6d4b\u8bd5\" id=\"siteForm\" enctype=\"multipart/form-data\"> \r\n<input type=\"hidden\" name=\"id\" id=\"id\" value=\"".toCharArray();
    _jsp_string20 = "\r\n		   	<input type=\"radio\" name=\"viewFlag\" value=\"0\" checked=\"checked\"/>\u662f<input type=\"radio\" name=\"viewFlag\" value=\"1\" />\u5426\r\n		   ".toCharArray();
    _jsp_string4 = "\"/>\r\n			".toCharArray();
    _jsp_string7 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u57df\u540d\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"domain\" value=\"".toCharArray();
    _jsp_string13 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u7535\u5b50\u90ae\u4ef6\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"email\" value=\"".toCharArray();
    _jsp_string16 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u7535\u8bdd\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"phone\" value=\"".toCharArray();
    _jsp_string19 = "\r\n			  <input type=\"radio\" name=\"viewFlag\" value=\"0\"/>\u662f<input type=\"radio\" name=\"viewFlag\" value=\"1\" checked=\"checked\"/>\u5426\r\n			 ".toCharArray();
    _jsp_string2 = "\"/>\r\n		</td>\r\n	</tr>\r\n  <tr>\r\n		<td width=\"80\">\r\n			\u7ad9\u70b9\u56fe\u7247\r\n		</td>\r\n		<td>\r\n			<input type=\"file\" name=\"pic\" />\r\n			".toCharArray();
    _jsp_string8 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u4e0a\u7ebf\u65f6\u95f4\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"onlineTime\" value=\"".toCharArray();
    _jsp_string15 = "\"/>\r\n		</td>\r\n	</tr>	\r\n			<tr>\r\n		<td width=\"80\">\r\n			MSN\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"msn\" value=\"".toCharArray();
    _jsp_string5 = "\r\n		</td>\r\n	</tr>	\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u9996\u9875\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"webPage\" value=\"".toCharArray();
    _jsp_string6 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u5730\u5740\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"address\" value=\"".toCharArray();
    _jsp_string14 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			QQ\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"qq\" value=\"".toCharArray();
  }
}
