/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._bms;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _comment__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    dms.tag.UserTag _jsp_UserTag_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_UserTag_0 == null) {
        _jsp_UserTag_0 = new dms.tag.UserTag();
        _jsp_UserTag_0.setPageContext(pageContext);
        _jsp_UserTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_UserTag_0.setUserId(new java.lang.Long(_caucho_expr_1.evalLong(_jsp_env)));
      _jsp_UserTag_0.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_2.print(out, _jsp_env, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_3.print(out, _jsp_env, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _caucho_expr_4.print(out, _jsp_env, false);
      out.write(_jsp_string5, 0, _jsp_string5.length);
      if (_caucho_expr_5.evalBoolean(_jsp_env)) {
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _caucho_expr_0.print(out, _jsp_env, false);
        out.write(_jsp_string7, 0, _jsp_string7.length);
      }
      else {
        out.write(_jsp_string8, 0, _jsp_string8.length);
        _caucho_expr_0.print(out, _jsp_env, false);
        out.write(_jsp_string7, 0, _jsp_string7.length);
      }
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string10, 0, _jsp_string10.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_UserTag_0 != null)
        _jsp_UserTag_0.release();
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
    manager.addTaglibFunctions(_jsp_functionMap, "mytld", "/tld/MyTld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.id}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.userId}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${target}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.content}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.createTime}");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.auditFlag==1}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("bms/comment.jsp"), 6558253358094695506L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/MyTld.tld"), 512393605891763069L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.UserTag.class, -4164810695213726271L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;

  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string9;
  private final static char []_jsp_string10;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  static {
    _jsp_string6 = "\r\n	<input type=\"button\" name=\"submit1\" value=\"\u5ba1\u6838\u901a\u8fc7\" onclick=\"location.href='comment.do?method=audit&type=0&id=".toCharArray();
    _jsp_string3 = "\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u5185\u5bb9\r\n		</td>\r\n		<td>\r\n			".toCharArray();
    _jsp_string4 = "\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u53d1\u5e03\u65f6\u95f4\r\n		</td>\r\n		<td>\r\n			<fmt:formatDate value=\"".toCharArray();
    _jsp_string8 = "\r\n	<input type=\"button\" name=\"submit1\" value=\"\u5ba1\u6838\u4e0d\u901a\u8fc7\" onclick=\"location.href='comment.do?method=audit&type=1&id=".toCharArray();
    _jsp_string9 = "\r\n	&nbsp;&nbsp;<input type=\"button\" name=\"reset1\" onclick=\"if confirm('\u786e\u5b9e\u5220\u9664\uff1f'){location.href='comment.do?method=delete&id=".toCharArray();
    _jsp_string10 = "'}\" value=\"\u5220\u9664\">&nbsp;&nbsp;<input type=\"button\" name=\"back\" value=\"\u8fd4\u56de\" onclick=\"history.go(-1);\"></p>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string5 = "\" pattern=\"yyyy-MM-dd HH:mm:ss\"/>\r\n		</td>\r\n	</tr>	\r\n</table>\r\n<p style=\"text-align:center\">\r\n	".toCharArray();
    _jsp_string1 = "\"/>\r\n<table width=\"90%\" border=\"1\" align=\"center\" cellpadding=\"0\"\r\n	cellspacing=\"0\" bordercolorlight=#AAAAAA bordercolordark=white>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u7528\u6237\u540d\r\n		</td>\r\n		<td>\r\n			".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\" />\r\n<meta name=\"description\" content=\" \">\r\n<meta name=\"keywords\" content=\" \">\r\n<title></title>\r\n</head>\r\n<body>\r\n<br>\r\n\r\n<input type=\"hidden\" name=\"id\" id=\"id\" value=\"".toCharArray();
    _jsp_string7 = "'\">\r\n".toCharArray();
    _jsp_string2 = "\r\n		</td>\r\n	</tr>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u88ab\u8bc4\u5185\u5bb9\r\n		</td>\r\n		<td>\r\n			".toCharArray();
  }
}
