/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._bms;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import dms.data.Info;

public class _info__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    dms.tag.CategorySelectTag _jsp_CategorySelectTag_0 = null;
    dms.tag.CitySelectTag _jsp_CitySelectTag_1 = null;
    dms.tag.DomainSelectTag _jsp_DomainSelectTag_2 = null;
    dms.tag.ServiceSelectTag _jsp_ServiceSelectTag_3 = null;
    dms.tag.GroupSelectTag _jsp_GroupSelectTag_4 = null;
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jsp_FormatDateTag_5 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_CategorySelectTag_0 == null) {
        _jsp_CategorySelectTag_0 = new dms.tag.CategorySelectTag();
        _jsp_CategorySelectTag_0.setPageContext(pageContext);
        _jsp_CategorySelectTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_CategorySelectTag_0.setName("category");
      }

      _jsp_CategorySelectTag_0.setCatId(new java.lang.Long(_caucho_expr_1.evalLong(_jsp_env)));
      _jsp_CategorySelectTag_0.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_jsp_CitySelectTag_1 == null) {
        _jsp_CitySelectTag_1 = new dms.tag.CitySelectTag();
        _jsp_CitySelectTag_1.setPageContext(pageContext);
        _jsp_CitySelectTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_CitySelectTag_1.setName("city");
      }

      _jsp_CitySelectTag_1.setCityId(new java.lang.Long(_caucho_expr_2.evalLong(_jsp_env)));
      _jsp_CitySelectTag_1.doStartTag();
      out.write(_jsp_string3, 0, _jsp_string3.length);
      if (_jsp_DomainSelectTag_2 == null) {
        _jsp_DomainSelectTag_2 = new dms.tag.DomainSelectTag();
        _jsp_DomainSelectTag_2.setPageContext(pageContext);
        _jsp_DomainSelectTag_2.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_DomainSelectTag_2.setName("siteId");
      }

      _jsp_DomainSelectTag_2.setDomainId(new java.lang.Long(_caucho_expr_3.evalLong(_jsp_env)));
      _jsp_DomainSelectTag_2.doStartTag();
      out.write(_jsp_string4, 0, _jsp_string4.length);
      if (_jsp_ServiceSelectTag_3 == null) {
        _jsp_ServiceSelectTag_3 = new dms.tag.ServiceSelectTag();
        _jsp_ServiceSelectTag_3.setPageContext(pageContext);
        _jsp_ServiceSelectTag_3.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_ServiceSelectTag_3.setName("service");
      }

      _jsp_ServiceSelectTag_3.setService(new java.lang.Long(_caucho_expr_4.evalLong(_jsp_env)));
      _jsp_ServiceSelectTag_3.doStartTag();
      out.write(_jsp_string5, 0, _jsp_string5.length);
      if (_jsp_GroupSelectTag_4 == null) {
        _jsp_GroupSelectTag_4 = new dms.tag.GroupSelectTag();
        _jsp_GroupSelectTag_4.setPageContext(pageContext);
        _jsp_GroupSelectTag_4.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_GroupSelectTag_4.setName("group");
      }

      _jsp_GroupSelectTag_4.setGroup(new java.lang.Long(_caucho_expr_5.evalLong(_jsp_env)));
      _jsp_GroupSelectTag_4.doStartTag();
      out.write(_jsp_string6, 0, _jsp_string6.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string7, 0, _jsp_string7.length);
      if (_jsp_FormatDateTag_5 == null) {
        _jsp_FormatDateTag_5 = new org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag();
        _jsp_FormatDateTag_5.setPageContext(pageContext);
        _jsp_FormatDateTag_5.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormatDateTag_5.setPattern("yy-MM-dd HH:mm:ss");
      }

      _jsp_FormatDateTag_5.setValue((java.util.Date) _caucho_expr_7.evalObject(_jsp_env));
      _jsp_FormatDateTag_5.doEndTag();
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _jsp_FormatDateTag_5.setValue((java.util.Date) _caucho_expr_8.evalObject(_jsp_env));
      _jsp_FormatDateTag_5.doEndTag();
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _caucho_expr_9.print(out, _jsp_env, false);
      out.write(_jsp_string10, 0, _jsp_string10.length);
      _caucho_expr_10.print(out, _jsp_env, false);
      out.write(_jsp_string11, 0, _jsp_string11.length);
      _caucho_expr_11.print(out, _jsp_env, false);
      out.write(_jsp_string12, 0, _jsp_string12.length);
      _caucho_expr_12.print(out, _jsp_env, false);
      out.write(_jsp_string13, 0, _jsp_string13.length);
      _caucho_expr_13.print(out, _jsp_env, false);
      out.write(_jsp_string14, 0, _jsp_string14.length);
      _caucho_expr_14.print(out, _jsp_env, false);
      out.write(_jsp_string15, 0, _jsp_string15.length);
      if (_caucho_expr_15.evalBoolean(_jsp_env)) {
        out.write(_jsp_string16, 0, _jsp_string16.length);
      }
      else {
        out.write(_jsp_string17, 0, _jsp_string17.length);
      }
      out.write(_jsp_string18, 0, _jsp_string18.length);
      _caucho_expr_16.print(out, _jsp_env, false);
      out.write(_jsp_string19, 0, _jsp_string19.length);
      _caucho_expr_17.print(out, _jsp_env, false);
      out.write(_jsp_string20, 0, _jsp_string20.length);
      _caucho_expr_18.print(out, _jsp_env, false);
      out.write(_jsp_string21, 0, _jsp_string21.length);
      _caucho_expr_19.print(out, _jsp_env, false);
      out.write(_jsp_string22, 0, _jsp_string22.length);
      if (_caucho_expr_20.evalBoolean(_jsp_env)) {
        out.write(_jsp_string23, 0, _jsp_string23.length);
      }
      else {
        out.write(_jsp_string24, 0, _jsp_string24.length);
      }
      out.write(_jsp_string25, 0, _jsp_string25.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_CategorySelectTag_0 != null)
        _jsp_CategorySelectTag_0.release();
      if (_jsp_CitySelectTag_1 != null)
        _jsp_CitySelectTag_1.release();
      if (_jsp_DomainSelectTag_2 != null)
        _jsp_DomainSelectTag_2.release();
      if (_jsp_ServiceSelectTag_3 != null)
        _jsp_ServiceSelectTag_3.release();
      if (_jsp_GroupSelectTag_4 != null)
        _jsp_GroupSelectTag_4.release();
      if (_jsp_FormatDateTag_5 != null)
        _jsp_FormatDateTag_5.release();
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
    manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jstl/fmt");
    manager.addTaglibFunctions(_jsp_functionMap, "fn", "http://java.sun.com/jstl/functions");
    manager.addTaglibFunctions(_jsp_functionMap, "mytld", "/tld/MyTld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.id}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.category}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.city}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.siteId}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.service}");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.group}");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.url1}");
    _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.startTime}");
    _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.endTime}");
    _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.orgPrice}");
    _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.sellPrice}");
    _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.discount}");
    _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.title}");
    _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.address}");
    _caucho_expr_14 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.userCount}");
    _caucho_expr_15 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.viewFlag==1}");
    _caucho_expr_16 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.phone}");
    _caucho_expr_17 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.webSite}");
    _caucho_expr_18 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.trafficInfo}");
    _caucho_expr_19 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.biefe}");
    _caucho_expr_20 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.ifTest==0}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("bms/info.jsp"), -3507448949258287785L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/MyTld.tld"), 2313055599944075409L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.CategorySelectTag.class, 4895540770968086576L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.CitySelectTag.class, -8095317528224568575L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.DomainSelectTag.class, -6906637344929707994L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.ServiceSelectTag.class, 1551605886958229292L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.GroupSelectTag.class, 8341835262871728445L));
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/fmt.tld"), 308338869353100094L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class, 7844905413159918656L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;
  private static com.caucho.el.Expr _caucho_expr_14;
  private static com.caucho.el.Expr _caucho_expr_15;
  private static com.caucho.el.Expr _caucho_expr_16;
  private static com.caucho.el.Expr _caucho_expr_17;
  private static com.caucho.el.Expr _caucho_expr_18;
  private static com.caucho.el.Expr _caucho_expr_19;
  private static com.caucho.el.Expr _caucho_expr_20;

  private final static char []_jsp_string13;
  private final static char []_jsp_string11;
  private final static char []_jsp_string8;
  private final static char []_jsp_string5;
  private final static char []_jsp_string2;
  private final static char []_jsp_string6;
  private final static char []_jsp_string7;
  private final static char []_jsp_string19;
  private final static char []_jsp_string15;
  private final static char []_jsp_string25;
  private final static char []_jsp_string1;
  private final static char []_jsp_string22;
  private final static char []_jsp_string24;
  private final static char []_jsp_string17;
  private final static char []_jsp_string12;
  private final static char []_jsp_string18;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  private final static char []_jsp_string14;
  private final static char []_jsp_string16;
  private final static char []_jsp_string3;
  private final static char []_jsp_string9;
  private final static char []_jsp_string23;
  private final static char []_jsp_string20;
  private final static char []_jsp_string10;
  private final static char []_jsp_string21;
  static {
    _jsp_string13 = "</textarea>\r\n		</td>\r\n	</tr>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u5730\u5740\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"address\" value=\"".toCharArray();
    _jsp_string11 = "\"/>\r\n		</td>\r\n	</tr>	\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u6298\u6263\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"discount\" value=\"".toCharArray();
    _jsp_string8 = "\" size=\"16\" onFocus=\"WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'})\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u7ed3\u675f\u65f6\u95f4\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"stime\" value=\"".toCharArray();
    _jsp_string5 = "\r\n		</td>\r\n	</tr>	\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u5546\u5708\r\n		</td>\r\n		<td>\r\n			&nbsp;".toCharArray();
    _jsp_string2 = "\r\n		</td>\r\n	</tr>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u57ce\u5e02\r\n		</td>\r\n		<td>\r\n			&nbsp;".toCharArray();
    _jsp_string6 = "\r\n		</td>\r\n	</tr>		\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u5f80\u671f\u5730\u5740\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"url1\" value=\"".toCharArray();
    _jsp_string7 = "\"/>\r\n		</td>\r\n	</tr>	\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u5f00\u59cb\u65f6\u95f4\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"stime\" value=\"".toCharArray();
    _jsp_string19 = "\"/>\r\n		</td>\r\n	</tr>		\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u7f51\u7ad9\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"webSite\" value=\"".toCharArray();
    _jsp_string15 = "\"/>\r\n		</td>\r\n	</tr>	\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u662f\u5426\u663e\u793a\r\n		</td>\r\n		<td>\r\n			".toCharArray();
    _jsp_string25 = "\r\n		</td>\r\n	</tr>		\r\n\r\n</table>\r\n<p style=\"text-align:center\"><input type=\"submit\" name=\"submit1\" value=\"\u63d0\u4ea4\">&nbsp;&nbsp;<input type=\"reset\" name=\"reset1\" value=\"\u53d6\u6d88\">&nbsp;&nbsp;<input type=\"button\" name=\"back\" value=\"\u8fd4\u56de\" onclick=\"history.go(-1);\"></p>\r\n</form>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string1 = "\"/>\r\n<table width=\"90%\" border=\"1\" align=\"center\" cellpadding=\"0\"\r\n	cellspacing=\"0\" bordercolorlight=#AAAAAA bordercolordark=white>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u56e2\u8d2d\u7c7b\u578b\r\n		</td>\r\n		<td>\r\n			&nbsp;".toCharArray();
    _jsp_string22 = "\"/>\r\n		</td>\r\n	</tr>		\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u8bd5\u56e2\r\n		</td>\r\n		<td>\r\n			".toCharArray();
    _jsp_string24 = "\r\n		   	<input type=\"radio\" name=\"ifTest\" value=\"0\" />\u662f<input type=\"radio\" name=\"ifTest\" value=\"1\" checked=\"checked\"/>\u5426\r\n		   ".toCharArray();
    _jsp_string17 = "\r\n		   	<input type=\"radio\" name=\"viewFlag\" value=\"0\" checked=\"checked\"/>\u662f<input type=\"radio\" name=\"viewFlag\" value=\"1\" />\u5426\r\n		   ".toCharArray();
    _jsp_string12 = "\"/>\r\n		</td>\r\n	</tr>		\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u6807\u9898\r\n		</td>\r\n		<td>\r\n			<textarea name=\"title\" rows=\"5\" cols=\"100\">".toCharArray();
    _jsp_string18 = "\r\n		 </td>\r\n	</tr>			\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u7535\u8bdd\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"phone\" value=\"".toCharArray();
    _jsp_string4 = "\r\n		</td>\r\n	</tr>	\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u670d\u52a1\r\n		</td>\r\n		<td>\r\n			&nbsp;".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\" />\r\n<meta name=\"description\" content=\" \">\r\n<meta name=\"keywords\" content=\" \">\r\n<title></title>\r\n<script src=\"../js/My97DatePicker46/WdatePicker.js\" defer=\"defer\"></script>\r\n</head>\r\n<body>\r\n<br>\r\n<form name=\"infoForm\" method=\"post\" action=\"info.do?method=edit\" id=\"infoForm\"> \r\n<input type=\"hidden\" name=\"id\" id=\"id\" value=\"".toCharArray();
    _jsp_string14 = "\"/>\r\n		</td>\r\n	</tr>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u7528\u6237\u6570\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"userCount\" value=\"".toCharArray();
    _jsp_string16 = "\r\n			  <input type=\"radio\" name=\"viewFlag\" value=\"0\"/>\u662f<input type=\"radio\" name=\"viewFlag\" value=\"1\" checked=\"checked\"/>\u5426\r\n			 ".toCharArray();
    _jsp_string3 = "\r\n		</td>\r\n	</tr>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u7ad9\u70b9\r\n		</td>\r\n		<td>\r\n			&nbsp;".toCharArray();
    _jsp_string9 = "\" size=\"16\" onFocus=\"WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'#F{$dp.$D(\\'stime\\')}'})\"/>\r\n		</td>\r\n	</tr>	\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u539f\u4ef7\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"orgPrice\" value=\"".toCharArray();
    _jsp_string23 = "\r\n			  <input type=\"radio\" name=\"ifTest\" value=\"0\" checked=\"checked\"/>\u662f<input type=\"radio\" name=\"ifTest\" value=\"1\" />\u5426\r\n			 ".toCharArray();
    _jsp_string20 = "\"/>\r\n		</td>\r\n	</tr>		\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u4ea4\u901a\u4fe1\u606f\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"trafficInfo\" value=\"".toCharArray();
    _jsp_string10 = "\"/>\r\n		</td>\r\n	</tr>\r\n		<tr>\r\n		<td width=\"80\">\r\n			\u552e\u4ef7\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"sellPrice\" value=\"".toCharArray();
    _jsp_string21 = "\"/>\r\n		</td>\r\n	</tr>		\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u7b80\u4ecb\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"biefe\" value=\"".toCharArray();
  }
}
