/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._bms;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import dms.data.Info;

public class _poi__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_2.evalBoolean(_jsp_env)) {
        out.write(_jsp_string3, 0, _jsp_string3.length);
        _caucho_expr_3.print(out, _jsp_env, false);
        out.write(_jsp_string4, 0, _jsp_string4.length);
        _caucho_expr_4.print(out, _jsp_env, false);
        out.write(_jsp_string5, 0, _jsp_string5.length);
      }
      out.write(_jsp_string6, 0, _jsp_string6.length);
      
String sinfoId=request.getParameter("infoId");
Long infoId=0l;
try{
infoId=Long.parseLong(sinfoId);
}catch(Exception e){}
request.setAttribute("infoId",infoId);

      out.write(_jsp_string7, 0, _jsp_string7.length);
      _caucho_expr_5.print(out, _jsp_env, false);
      out.write(_jsp_string8, 0, _jsp_string8.length);
      _caucho_expr_6.print(out, _jsp_env, false);
      out.write(_jsp_string9, 0, _jsp_string9.length);
      _caucho_expr_3.print(out, _jsp_env, false);
      out.write(_jsp_string10, 0, _jsp_string10.length);
      _caucho_expr_4.print(out, _jsp_env, false);
      out.write(_jsp_string11, 0, _jsp_string11.length);
      _caucho_expr_7.print(out, _jsp_env, false);
      out.write(_jsp_string12, 0, _jsp_string12.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
    manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jstl/fmt");
    manager.addTaglibFunctions(_jsp_functionMap, "fn", "http://java.sun.com/jstl/functions");
    manager.addTaglibFunctions(_jsp_functionMap, "mytld", "/tld/MyTld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj==null?(3990872):(obj.lat)}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj==null?(11639728):(obj.lon)}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj!=null}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.lat}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.lon}");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.id}");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj!=null?(obj.infoId):(infoId)}");
    _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.address}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("bms/poi.jsp"), -1238056795751430929L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;

  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string10;
  private final static char []_jsp_string12;
  private final static char []_jsp_string7;
  private final static char []_jsp_string8;
  private final static char []_jsp_string11;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string5;
  private final static char []_jsp_string9;
  static {
    _jsp_string6 = "\r\n  });\r\n  \r\n  \r\n</script>\r\n</head>\r\n<body>\r\n<br>\r\n".toCharArray();
    _jsp_string3 = "\r\n  	var latlng = new google.maps.LatLng(".toCharArray();
    _jsp_string4 = "/100000,".toCharArray();
    _jsp_string10 = "\"/>\r\n<input type=\"hidden\" name=\"lon\" id=\"lon\" value=\"".toCharArray();
    _jsp_string12 = "\"  size=\"80\"/>\r\n		</td>\r\n	</tr>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u5730\u56fe\u6807\u70b9\r\n		</td>\r\n		<td>\r\n			<div id=\"map_canvas\" style=\"height:500px;width:800px\" ></div>\r\n		</td>\r\n	</tr>\r\n</table>\r\n<p style=\"text-align:center\"><input type=\"submit\" name=\"submit1\" value=\"\u63d0\u4ea4\">&nbsp;&nbsp;<input type=\"reset\" name=\"reset1\" value=\"\u53d6\u6d88\">&nbsp;&nbsp;<input type=\"button\" name=\"back\" value=\"\u8fd4\u56de\" onclick=\"history.go(-1);\"></p>\r\n</form>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string7 = "\r\n<form name=\"addressForm\" method=\"post\" action=\"poi.do?method=edit\" id=\"addressForm\"> \r\n<input type=\"hidden\" name=\"id\" id=\"id\" value=\"".toCharArray();
    _jsp_string8 = "\"/>\r\n<input type=\"hidden\" name=\"infoId\" id=\"infoId\" value=\"".toCharArray();
    _jsp_string11 = "\"/>\r\n<table width=\"90%\" border=\"1\" align=\"center\" cellpadding=\"0\"\r\n	cellspacing=\"0\" bordercolorlight=#AAAAAA bordercolordark=white>\r\n	<tr>\r\n		<td width=\"80\">\r\n			\u5730\u5740\r\n		</td>\r\n		<td>\r\n			<input type=\"text\" name=\"address\" value=\"".toCharArray();
    _jsp_string2 = "/100000;\r\n    var latlng = new google.maps.LatLng(lat,lon);\r\n    var myOptions = {\r\n      zoom: 12,\r\n      center: latlng,\r\n      mapTypeId: google.maps.MapTypeId.ROADMAP\r\n    }\r\n    map = new google.maps.Map(document.getElementById(\"map_canvas\"), myOptions);\r\n    \r\n   google.maps.event.addListener(map, 'click', function(event) {\r\n   	map.clearMarkers();\r\n    addPoint(event.latLng);\r\n  }); \r\n    \r\n  }\r\n  \r\n  function addPoint(latlon){\r\n  	  var marker = new google.maps.Marker({ \r\n      position: latlon,  \r\n      map: map,  \r\n      title:\"\u65b0\u6807\u70b9\" \r\n    });\r\n    //alert(latlon.lat()+\",\"+latlon.lng());\r\n    jQuery(\"#lat\").val(parseInt(latlon.lat()*100000));\r\n    jQuery(\"#lon\").val(parseInt(latlon.lng()*100000));    \r\n  }\r\n  \r\n  function addPoint1(lat,lon){\r\n  	var latlng = new google.maps.LatLng(lat,lon);\r\n  	addPoint(latlng);\r\n  }\r\n  \r\n  \r\n  jQuery(function(){\r\n  	initialize();\r\n  	".toCharArray();
    _jsp_string1 = "/100000;\r\n    var lon=".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\" />\r\n<meta name=\"description\" content=\" \">\r\n<meta name=\"keywords\" content=\" \">\r\n<title>\u5730\u5740</title>\r\n<script type=\"text/javascript\" src=\"../js/jquery-1.4.2g.js\"></script>\r\n<script src=\"../js/My97DatePicker46/WdatePicker.js\" defer=\"defer\"></script>\r\n<script type=\"text/javascript\" src=\"http://maps.google.com/maps/api/js?sensor=false\"></script>\r\n<script src=\"../js/markers.js\" ></script>\r\n<script>\r\nvar map;\r\n	  function initialize() {\r\n    geocoder = new google.maps.Geocoder();\r\n    var lat=".toCharArray();
    _jsp_string5 = "/100000);\r\n  	addPoint(latlng);\r\n  	map.setCenter(latlng);\r\n  	".toCharArray();
    _jsp_string9 = "\"/>\r\n<input type=\"hidden\" name=\"lat\" id=\"lat\" value=\"".toCharArray();
  }
}
