/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._bms;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _poilist__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      out.print((request.getContextPath()));
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      if (_caucho_expr_1.evalBoolean(_jsp_env)) {
        out.write(_jsp_string3, 0, _jsp_string3.length);
        if (_jsp_loop_0 == null)
          _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
        java.lang.Object _jsp_items_1 = _caucho_expr_2.evalObject(_jsp_env);
        java.util.Iterator _jsp_iter_1 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_1);
        _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
        Object _jsp_status_1 = pageContext.putAttribute("index", _jsp_loop_0);
        Object _jsp_oldVar_1 = pageContext.getAttribute("obj");
        while (_jsp_iter_1.hasNext()) {
          Object _jsp_i_1 = _jsp_iter_1.next();
          pageContext.setAttribute("obj", _jsp_i_1);
          _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
          out.write(_jsp_string4, 0, _jsp_string4.length);
          _caucho_expr_3.print(out, _jsp_env, false);
          out.write(_jsp_string5, 0, _jsp_string5.length);
          _caucho_expr_4.print(out, _jsp_env, false);
          out.write(_jsp_string5, 0, _jsp_string5.length);
          _caucho_expr_5.print(out, _jsp_env, false);
          out.write(_jsp_string6, 0, _jsp_string6.length);
          _caucho_expr_6.print(out, _jsp_env, false);
          out.write(_jsp_string7, 0, _jsp_string7.length);
          _caucho_expr_7.print(out, _jsp_env, false);
          out.write(_jsp_string8, 0, _jsp_string8.length);
          _caucho_expr_7.print(out, _jsp_env, false);
          out.write(_jsp_string9, 0, _jsp_string9.length);
          if (_caucho_expr_8.evalBoolean(_jsp_env)) {
            out.write(_jsp_string10, 0, _jsp_string10.length);
            _caucho_expr_5.print(out, _jsp_env, false);
            out.write(_jsp_string11, 0, _jsp_string11.length);
            _caucho_expr_4.print(out, _jsp_env, false);
            out.write(_jsp_string12, 0, _jsp_string12.length);
            _caucho_expr_3.print(out, _jsp_env, false);
            out.write(_jsp_string13, 0, _jsp_string13.length);
            _caucho_expr_6.print(out, _jsp_env, false);
            out.write(_jsp_string14, 0, _jsp_string14.length);
          }
          out.write(_jsp_string15, 0, _jsp_string15.length);
        }
        pageContext.pageSetOrRemove("obj", _jsp_oldVar_1);
        pageContext.removeAttribute("index");
        out.write(_jsp_string16, 0, _jsp_string16.length);
      }
      out.write(_jsp_string17, 0, _jsp_string17.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
    manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jstl/fmt");
    manager.addTaglibFunctions(_jsp_functionMap, "fn", "http://java.sun.com/jstl/functions");
    manager.addTaglibFunctions(_jsp_functionMap, "mytld", "/tld/MyTld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${infoId}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list!=null&&!empty list}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.address}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.lon}");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.lat}");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${index.index*32}");
    _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.id}");
    _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.lat!=null&&obj.lon!=null}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("bms/poiList.jsp"), -7423410279448287296L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;

  private final static char []_jsp_string0;
  private final static char []_jsp_string10;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string11;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string8;
  private final static char []_jsp_string13;
  private final static char []_jsp_string14;
  private final static char []_jsp_string12;
  private final static char []_jsp_string16;
  private final static char []_jsp_string4;
  private final static char []_jsp_string15;
  private final static char []_jsp_string9;
  private final static char []_jsp_string7;
  private final static char []_jsp_string17;
  private final static char []_jsp_string3;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<title>\u56e2\u8d2d\u5217\u8868</title>\r\n<link href=\"../css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<script src=\"../js/li_ddrivetip_2.js\"></script>\r\n<script type=\"text/javascript\" src=\"../js/jquery-1.4.2g.js\"></script>\r\n<script src=\"../js/My97DatePicker46/WdatePicker.js\" defer=\"defer\"></script>\r\n<script src=\"../js/formtools.js\"></script>\r\n<script src=\"".toCharArray();
    _jsp_string10 = "\r\n<script>\r\n	jQuery(function(){\r\n		var latlon=new google.maps.LatLng(".toCharArray();
    _jsp_string1 = "/js/bmsPage.js\" type=\"text/javascript\"></script>\r\n<script type=\"text/javascript\" src=\"http://maps.google.com/maps/api/js?sensor=false\"></script>\r\n<script src=\"../js/markers.js\" ></script>\r\n<script>\r\nvar map;\r\nvar bounds;\r\nvar count=0;\r\n	  function initialize() {\r\n    var lat=3990872/100000;\r\n    var lon=11639728/100000;\r\n    var latlng = new google.maps.LatLng(lat,lon);\r\n    var myOptions = {\r\n      zoom: 12,\r\n      center: latlng,\r\n      mapTypeId: google.maps.MapTypeId.ROADMAP\r\n    }\r\n    map = new google.maps.Map(document.getElementById(\"map_canvas\"), myOptions);\r\n    bounds = new google.maps.LatLngBounds();\r\n  }\r\n  \r\n  function addPoint(latlon,icon,title){\r\n  	  var marker = new google.maps.Marker({\r\n      position: latlon,  \r\n      map: map,  \r\n      icon:icon,\r\n      title:title\r\n    });\r\n  }\r\n  \r\n  \r\n  jQuery(function(){\r\n  	initialize();\r\n  });\r\n  \r\n  \r\n</script>\r\n</head>\r\n<body style=\"background:#deeef6;\">\r\n<div>\r\n  <div>\r\n      <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" >\r\n        <tr>\r\n          <td width=\"25\" height=\"23\"><img src=\"../images/list_ico.gif\" alt=\"\" width=\"20\" height=\"23\" /></td>\r\n          <td><span class=\"bold\">\u5730\u5740\u5217\u8868</span></td>\r\n          <td></td>\r\n          <td width=\"120\"><a href=\"info.do?method=list&p=1\">\u56e2\u8d2d\u5217\u8868</a>&nbsp;&nbsp;<a href=\"poi.jsp?infoId=".toCharArray();
    _jsp_string2 = "\">\u65b0\u589e</a></td>\r\n        </tr>\r\n      </table>\r\n <table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\">\r\n <tr>\r\n<th>\u5730\u5740</th>\r\n<th>\u7ecf\u5ea6</th>\r\n<th>\u7eac\u5ea6</th>\r\n<th>\u6807\u70b9</th>\r\n<th>\u64cd\u4f5c</th>\r\n</tr>\r\n    ".toCharArray();
    _jsp_string11 = "/100000,".toCharArray();
    _jsp_string5 = "</td>\r\n<td>".toCharArray();
    _jsp_string6 = "</td>\r\n<td>\r\n<div style=\"float:left;height:32px;margin-right:4px;width:20px;background:url('../images/green.png') repeat scroll 0pt -".toCharArray();
    _jsp_string8 = "\">\u7f16\u8f91</a>&nbsp;&nbsp;\r\n<a href=\"#\" onclick='if (confirm(\"\u786e\u8ba4\u5220\u9664\uff1f\")){location.href=\"poi.do?method=delete&id=".toCharArray();
    _jsp_string13 = "';\r\n		var icon = new google.maps.MarkerImage(\"../images/green.png\",\r\n                                new google.maps.Size(20, 32),\r\n                                new google.maps.Point(0,".toCharArray();
    _jsp_string14 = "))\r\n		addPoint(latlon,icon,title);\r\n		bounds.extend(latlon);\r\n		if(count == 0)\r\n  	{\r\n  		map.setCenter(latlon);\r\n  	}else\r\n  	{\r\n  		map.fitBounds(bounds);\r\n  	}\r\n	});\r\n</script>\r\n".toCharArray();
    _jsp_string12 = "/100000);\r\n		var title='".toCharArray();
    _jsp_string16 = "\r\n    ".toCharArray();
    _jsp_string4 = "      \r\n<tr>\r\n<td>".toCharArray();
    _jsp_string15 = "\r\n</td>\r\n</tr>\r\n	      ".toCharArray();
    _jsp_string9 = "\";};return false;'>\u5220\u9664</a>&nbsp;&nbsp;\r\n".toCharArray();
    _jsp_string7 = "px transparent;\" title=\"\"></div>\r\n</td>\r\n<td>\r\n<a href=\"poi.do?method=view&id=".toCharArray();
    _jsp_string17 = " \r\n  </table>\r\n\r\n    </div>\r\n  </div>\r\n<p></p>\r\n\r\n<div id=\"map_canvas\" style=\"height:500px;width:800px\" ></div>\r\n<div></div>\r\n\r\n</body>\r\n<script>\r\njQuery(function(){\r\n});\r\n</script>\r\n\r\n</html>\r\n".toCharArray();
    _jsp_string3 = "\r\n      ".toCharArray();
  }
}
