/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp._bms;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import dms.data.Sites;
import dms.data.Rules;
import dms.data.City;
import java.util.List;
import org.dom4j.Document;
import org.dom4j.Element;
import org.dom4j.io.SAXReader;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Iterator;
import util.DbUtil;
import org.springframework.web.util.HtmlUtils;

public class _xml__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;

  public void viewElement(Element e, PrintWriter out, int level,long id) {
  
  //System.out.println("name:"+e.getName());
  		String tagName = e.getName();
  		if (tagName == null)
  			return;
  
  		try {
  			if (tagName.equalsIgnoreCase("seg")) {
  			//System.out.println("seg");
  				String isNew = e.attributeValue("new");
  				String isLoop = e.attributeValue("loop");
  				String sid = e.attributeValue("ID");
  				String start = e.elementText("start");
  				String end = e.elementText("end");
  				out.write("<div style='margin-left:" + (level + 1) + "em' >");
  				out.write("<form id='form" + sid + "' name='form" + sid
  						+ "' method='post' action='rule.do?method=editSeg'>");
  				out.write("\u533a\u5757:");
  				out.write("<input type='hidden' name='id' value='" + id
  						+ "'/>");
  				out.write("<input type='hidden' name='fid' value='" + sid
  						+ "'/>");
  				if (isLoop != null && isLoop.equals("0")) {
  					out
  							.write("\u662f\u5426\u5faa\u73af:<input type='radio' name='isLoop' value='0'  checked='true'/>\u662f<input type='radio' name='isLoop' value='1'/>\u5426");
  				} else {
  					out
  							.write("\u662f\u5426\u5faa\u73af:<input type='radio' name='isLoop' value='0'/>\u662f<input type='radio' name='isLoop' value='1' checked='true'/>\u5426");
  				}
  				//out.write("<br/>");
  				if (isNew != null && isNew.equals("0")) {
  					out
  							.write("\u65b0\u8bb0\u5f55:<input type='radio' name='isNew' value='0'  checked='true'/>\u662f<input type='radio' name='isNew' value='1'/>\u5426");
  				} else {
  					out
  							.write("\u65b0\u8bb0\u5f55:<input type='radio' name='isNew' value='0'/>\u662f<input type='radio' name='isNew' value='1' checked='true'/>\u5426");
  				}
  				//out.write("<br/>");
  				out.write("\u5f00\u59cb:<input type='text' name='start' value='" + start
  						+ "'/>");
  				//out.write("<br/>");
  				out.write("\u7ed3\u675f:<input type='text' name='end' value='" + end
  						+ "'/>");
  				//out.write("<br/>");
  				out.write("<input type='submit' name='submit1' value='\u63d0\u4ea4'>");
  				out.write("<input type='button' name='add' id='xml"+sid+"' value='\u6dfb\u52a0\u5b50\u89c4\u5219' onclick='jQuery(this).addRule({\"fid\":\""+sid+"\",\"ftype\":0,\"init\":1,\"id\":"+id+"});'/>");
  				out.write("<input type='button' name='add' id='xml_"+sid+"' value='\u6dfb\u52a0\u540e\u7eed\u89c4\u5219' onclick='jQuery(this).addRule({\"fid\":\""+sid+"\",\"ftype\":1,\"init\":1,\"id\":"+id+"});'/>");
  				out.write("<input type='button' name='add' id='xml1"+sid+"' value='\u5220\u9664' onclick='deleteRule("+id+",\""+sid+"\");'/>");
  				out.write("</form>");
  				
  				//out.write("<br/>");
  				//out.write("<br/>");
  				
  
  				Iterator it = e.elementIterator();
  				while (it.hasNext()) {
  					viewElement((Element) it.next(), out, level + 1,id);
  				}
  
  				out.write("</div>");
  
  			} else if (tagName.equalsIgnoreCase("value")) {
  				String sid = e.attributeValue("ID");
  				String name = e.elementText("name");
  				String reg = e.elementText("reg");
  				reg = HtmlUtils.htmlEscape(reg);
  				out.write("<div style='margin-left:" + (level + 1) + "em' >");
  				out.write("<form id='form" + sid + "' name='form" + sid
  						+ "' method='post' action='rule.do?method=editValue'>");
  
                  out.write("\u8bbe\u503c:");
  				out.write("<input type='hidden' name='id' value='" + id
  						+ "'/>");
  				out.write("<input type='hidden' name='fid' value='" + sid
  						+ "'/>");
  				out.write("\u5b57\u6bb5:");
  				try {
  					StringBuffer buf = new StringBuffer();
  					buf.append("<select name='").append("name").append("' ");
  					buf.append(">");
  
  					String sql = "select column_name, column_comment from information_schema.columns where table_schema ='tuan'  and table_name = 'info'";
  					List list = DbUtil.getDao().list(sql, null, -1, -1);
  
  					for (Object o : list) {
  						Object[] os = (Object[]) o;
  						buf.append("<option value='").append(os[0])
  								.append("' ");
  
  						if (name != null
  								&& name.equalsIgnoreCase(os[0].toString())) {
  							buf.append(" selected='true' ");
  						}
  
  						buf.append(">").append(os[1]).append("</option>");
  					}
  
  					buf.append("</select>");
  
  					out.write(buf.toString());
  				} catch (Exception ex) {
  					ex.printStackTrace();
  					try {
  						out.write("\u9009\u62e9\u6807\u7b7e\u51fa\u9519!" + ex.toString());
  					} catch (Exception ex1) {
  						ex1.printStackTrace();
  					}
  				}
  				//out.write("<br/>");
  				out.write("\u6b63\u5219:<input type='text' name='reg' value='" + reg
  						+ "'/>");
  				//out.write("<br/>");
  				out.write("<input type='submit' name='submit1' value='\u63d0\u4ea4'>");
  				out.write("<input type='button' name='add' id='xml_"+sid+"' value='\u6dfb\u52a0\u540e\u7eed\u89c4\u5219' onclick='jQuery(this).addRule({\"fid\":\""+sid+"\",\"ftype\":1,\"init\":1,\"id\":"+id+"});'/>");
  				out.write("<input type='button' name='add' id='xml1"+sid+"' value='\u5220\u9664' onclick='deleteRule("+id+",\""+sid+"\");'/>");
  				out.write("</form>");
  								
  				//out.write("<br/>");
  				//out.write("<input type='button' name='add' id='xml"+sid+"' value='\u6dfb\u52a0\u5b50\u89c4\u5219' onclick='jQuery(this).addRule({\"fid\":"+sid+",\"ftype\":0,\"init\":1});'/>");
  				//out.write("<br/>");
  				
  				out.write("</div>");
  
  			} else if (tagName.equalsIgnoreCase("spider")) {
  				String isNew = e.attributeValue("new");
  				String sid = e.attributeValue("ID");
  				String reg = e.elementText("reg");
  				reg = HtmlUtils.htmlEscape(reg);
  
  				out.write("<div style='margin-left:" + (level + 1) + "em' >");
  				out.write("<form id='form" + sid + "' name='form" + sid
  						+ "' method='post' action='rule.do?method=editSpider'>");
  				out.write("\u6293\u53d6:");
  				out.write("<input type='hidden' name='id' value='" + id
  						+ "'/>");
  				out.write("<input type='hidden' name='fid' value='" + sid
  						+ "'/>");
  				if (isNew != null && isNew.equals("0")) {
  					out
  							.write("\u65b0\u8bb0\u5f55:<input type='radio' name='isNew' value='0'  checked='true'/>\u662f<input type='radio' name='isNew' value='1'/>\u5426");
  				} else {
  					out
  							.write("\u65b0\u8bb0\u5f55:<input type='radio' name='isNew' value='0'/>\u662f<input type='radio' name='isNew' value='1' checked='true'/>\u5426");
  				}
  				//out.write("<br/>");
  				out.write("\u6b63\u5219:<input type='text' name='reg' value='" + reg
  						+ "'/>");
  				//out.write("<br/>");
  				out.write("<input type='submit' name='submit1' value='\u63d0\u4ea4'>");
  				out.write("<input type='button' name='add' id='xml"+sid+"' value='\u6dfb\u52a0\u5b50\u89c4\u5219' onclick='jQuery(this).addRule({\"fid\":\""+sid+"\",\"ftype\":0,\"init\":1,\"id\":"+id+"});'/>");
  				out.write("<input type='button' name='add' id='xml_"+sid+"' value='\u6dfb\u52a0\u540e\u7eed\u89c4\u5219' onclick='jQuery(this).addRule({\"fid\":\""+sid+"\",\"ftype\":1,\"init\":1,\"id\":"+id+"});'/>");
  				out.write("<input type='button' name='add' id='xml1"+sid+"' value='\u5220\u9664' onclick='deleteRule("+id+",\""+sid+"\");'/>");
  				out.write("</form>");
  				
  				//out.write("<br/>");
  				//out.write("<br/>");
  
  				Iterator it = e.elementIterator();
  				while (it.hasNext()) {
  					viewElement((Element) it.next(), out, level + 1,id);
  				}
  
  				out.write("</div>");
  
  			}else{
  				Iterator it = e.elementIterator();
  				while (it.hasNext()) {
  					viewElement((Element) it.next(), out, level + 1,id);
  				}
  			}
  		} catch (Exception e1) {
  			e1.printStackTrace();
  		}
  	}
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    dms.tag.DomainSelectTag _jsp_DomainSelectTag_0 = null;
    dms.tag.CitySelectTag _jsp_CitySelectTag_1 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      out.print((request.getContextPath()));
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((request.getContextPath()));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((request.getContextPath()));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((request.getContextPath()));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
	String url = "";
	String charset = "UTF-8";
	String city = "";

	Rules rule = (Rules) request.getAttribute("obj");
	if (rule != null && rule.getRuleXml() != null) {
		InputStream in = new ByteArrayInputStream(rule.getRuleXml()
				.getBytes("UTF-8"));
		Document document = new SAXReader().read(in);

		Element root = document.getRootElement();

		url = root.elementText("url");
		if (url==null) url="";
		charset = root.elementText("charset");
		if (charset==null) charset="";
		city = root.elementText("city");

      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
      if (_jsp_DomainSelectTag_0 == null) {
        _jsp_DomainSelectTag_0 = new dms.tag.DomainSelectTag();
        _jsp_DomainSelectTag_0.setPageContext(pageContext);
        _jsp_DomainSelectTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_DomainSelectTag_0.setName("domain");
      }

      _jsp_DomainSelectTag_0.setDomainId(new java.lang.Long(_caucho_expr_1.evalLong(_jsp_env)));
      _jsp_DomainSelectTag_0.doStartTag();
      out.write(_jsp_string7, 0, _jsp_string7.length);
      if (_jsp_CitySelectTag_1 == null) {
        _jsp_CitySelectTag_1 = new dms.tag.CitySelectTag();
        _jsp_CitySelectTag_1.setPageContext(pageContext);
        _jsp_CitySelectTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_CitySelectTag_1.setName("city");
      }

      _jsp_CitySelectTag_1.setCityId(new java.lang.Long(_caucho_expr_2.evalLong(_jsp_env)));
      _jsp_CitySelectTag_1.doStartTag();
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((url));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((charset));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string11, 0, _jsp_string11.length);
      
			 	viewElement(root, response.getWriter(), 0,rule.getId());

			 	} else {
			 
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
      if (_jsp_DomainSelectTag_0 == null) {
        _jsp_DomainSelectTag_0 = new dms.tag.DomainSelectTag();
        _jsp_DomainSelectTag_0.setPageContext(pageContext);
        _jsp_DomainSelectTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_DomainSelectTag_0.setName("domain");
      }

      _jsp_DomainSelectTag_0.setDomainId(new java.lang.Long(_caucho_expr_1.evalLong(_jsp_env)));
      _jsp_DomainSelectTag_0.doStartTag();
      out.write(_jsp_string7, 0, _jsp_string7.length);
      if (_jsp_CitySelectTag_1 == null) {
        _jsp_CitySelectTag_1 = new dms.tag.CitySelectTag();
        _jsp_CitySelectTag_1.setPageContext(pageContext);
        _jsp_CitySelectTag_1.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_CitySelectTag_1.setName("city");
      }

      _jsp_CitySelectTag_1.setCityId(new java.lang.Long(_caucho_expr_2.evalLong(_jsp_env)));
      _jsp_CitySelectTag_1.doStartTag();
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((url));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((charset));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string11, 0, _jsp_string11.length);
      
	}

      out.write(_jsp_string12, 0, _jsp_string12.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string13, 0, _jsp_string13.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_DomainSelectTag_0 != null)
        _jsp_DomainSelectTag_0.release();
      if (_jsp_CitySelectTag_1 != null)
        _jsp_CitySelectTag_1.release();
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
    manager.addTaglibFunctions(_jsp_functionMap, "mytld", "/tld/MyTld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.id}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.domainId}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.city}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("bms/xml.jsp"), 82508870661997031L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/MyTld.tld"), 512393605891763069L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.DomainSelectTag.class, -6906637344929707994L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.CitySelectTag.class, -8095317528224568575L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;

  private final static char []_jsp_string12;
  private final static char []_jsp_string7;
  private final static char []_jsp_string5;
  private final static char []_jsp_string10;
  private final static char []_jsp_string9;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string11;
  private final static char []_jsp_string13;
  static {
    _jsp_string12 = "\r\n<a href=\"rule.do?method=list\" >\u8fd4\u56de\u5217\u8868</a>\r\n<a href=\"#\" onclick=\"test(".toCharArray();
    _jsp_string7 = "<br/>\r\n\u57ce\u5e02:".toCharArray();
    _jsp_string5 = "\r\n<form name=\"xmlForm\" id=\"xmlForm\" action=\"rule.do?method=editRule\" method=\"post\">\r\n<input type=\"hidden\" name=\"id\" value=\"".toCharArray();
    _jsp_string10 = "'/><br/>\r\n<input type=\"submit\" name=\"submit1\" value=\"\u63d0\u4ea4\"/>\r\n</form>\r\n<input type='button' name='add' id=\"xml0\" value='\u6dfb\u52a0\u5b50\u89c4\u5219' onclick='jQuery(this).addRule({\"fid\":0,\"ftype\":0,\"init\":1,\"id\":".toCharArray();
    _jsp_string9 = "'/><br/>\r\n\u7f16\u7801:<input type='text' name='charset' id='charset' value='".toCharArray();
    _jsp_string6 = "\"/>\r\n\u7f51\u7ad9\uff1a".toCharArray();
    _jsp_string3 = "/js/jquery-1.4.2g.js\" type=\"text/javascript\"></script>\r\n	<script src=\"".toCharArray();
    _jsp_string2 = "/style/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n	<script src=\"".toCharArray();
    _jsp_string4 = "/js/rule.js\" type=\"text/javascript\"></script>\r\n	<script>\r\n	function deleteRule(id,fid){\r\n	if (confirm(\"\u786e\u5b9a\u5220\u9664\u5417\uff1f\u64cd\u4f5c\u4e0d\u53ef\u6062\u590d\uff01\")){\r\n	location.href=\"rule.do?method=deleteRule&id=\"+id+\"&fid=\"+fid;\r\n}\r\n	}\r\n	\r\n	function test(id){\r\n		jQuery(\"#testView\").empty();\r\n	 jQuery.ajax({\r\n	 	'url' : 'rule.do?method=crawl',\r\n		'data' : {\r\n							'id' : id\r\n				},\r\n		//'dataType' : 'json',\r\n		'success' : function(data) {\r\n			jQuery(\"#testView\").html(data);\r\n		 }\r\n	 });\r\n	\r\n	\r\n	}\r\n	\r\n	\r\n	</script>\r\n	<style>\r\n	.td{\r\n  line-height:20px;\r\n  border-top:1px solid #FDFFFC;\r\n  border-left:2px solid #ffffff;\r\n  border-right:1px solid #9D9D9D;\r\n  border-bottom:1px solid #B3B3B3;\r\n  background:#E7E7E7;\r\n  valign:\"top\"\r\n  }\r\n		</style>\r\n	\r\n</head>\r\n<body>\r\n".toCharArray();
    _jsp_string8 = "<br/>\r\n\u5730\u5740url:<input type='text' name='url' id='url' value='".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n	<link href=\"".toCharArray();
    _jsp_string1 = "/style/bms.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n<link href=\"".toCharArray();
    _jsp_string11 = " });'/>\r\n".toCharArray();
    _jsp_string13 = ");return false;\">\u6d4b\u8bd5\u6293\u53d6</a>\r\n<div id=\"testView\"></div>\r\n</body>\r\n</html>".toCharArray();
  }
}
