<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://wsntim.ctsi.com.cn" xmlns:intf="http://wsntim.ctsi.com.cn" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://wsntim.ctsi.com.cn">
	<wsdl:types/>
	
	<wsdl:message name="CRMWSRequest">
	<wsdl:part name="WebServiceRequset" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="CRMWSResponse">
		<wsdl:part name="WebServiceResponse" type="xsd:string"/>
	</wsdl:message>
	<wsdl:portType name="CRMWebService">
		<wsdl:operation name="businessManager">
			<wsdl:input message="impl:CRMWSRequest" name="CRMWSRequest"/>
			<wsdl:output message="impl:CRMWSResponse" name="CRMWSResponse"/>
		</wsdl:operation>
	</wsdl:portType>

	
	<wsdl:binding name="CRMWebServiceSoapBinding" type="intf:CRMWebService">
		<wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="businessManager">
			<wsdlsoap:operation soapAction=""/>
			<wsdl:input name="CRMWSRequest">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost:8080/axis/services/CRMWebService" use="encoded"/>
			</wsdl:input>
			<wsdl:output name="CRMWSResponse">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/ encoding/" namespace="http://localhost:8080/axis/services/CRMWebService" use="encoded"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	

	
	<wsdl:service name="CRMWebService">
		<wsdl:port binding="intf:CRMWebServiceSoapBinding" name="CRMWebService">
			<wsdlsoap:address location="http://localhost:8080/axis/services/CRMWebService"/>
		</wsdl:port>
	</wsdl:service>
		
</wsdl:definitions>
