/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _map1__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    dms.tag.DomainTag _jsp_DomainTag_0 = null;
    dms.tag.StringTag _jsp_StringTag_1 = null;
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_1 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_caucho_expr_0.evalBoolean(_jsp_env)) {
        out.write(_jsp_string1, 0, _jsp_string1.length);
        if (_jsp_loop_0 == null)
          _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
        _jsp_loop_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        java.lang.Object _jsp_items_2 = _caucho_expr_1.evalObject(_jsp_env);
        java.util.Iterator _jsp_iter_2 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_2);
        _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
        Object _jsp_status_2 = pageContext.putAttribute("index", _jsp_loop_0);
        Object _jsp_oldVar_2 = pageContext.getAttribute("obj");
        while (_jsp_iter_2.hasNext()) {
          Object _jsp_i_2 = _jsp_iter_2.next();
          pageContext.setAttribute("obj", _jsp_i_2);
          _jsp_loop_0.setCurrent(_jsp_i_2, _jsp_iter_2.hasNext());
          out.write(_jsp_string2, 0, _jsp_string2.length);
          _caucho_expr_2.print(out, _jsp_env, false);
          out.write(_jsp_string3, 0, _jsp_string3.length);
          _caucho_expr_3.print(out, _jsp_env, false);
          out.write(_jsp_string4, 0, _jsp_string4.length);
          if (_jsp_DomainTag_0 == null) {
            _jsp_DomainTag_0 = new dms.tag.DomainTag();
            _jsp_DomainTag_0.setPageContext(pageContext);
            _jsp_DomainTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_loop_0);
          }

          _jsp_DomainTag_0.setDomainId(new java.lang.Long(_caucho_expr_3.evalLong(_jsp_env)));
          _jsp_DomainTag_0.doStartTag();
          out.write(_jsp_string5, 0, _jsp_string5.length);
          _caucho_expr_4.print(out, _jsp_env, false);
          out.write(_jsp_string6, 0, _jsp_string6.length);
          _caucho_expr_5.print(out, _jsp_env, false);
          out.write(_jsp_string7, 0, _jsp_string7.length);
          _caucho_expr_6.print(out, _jsp_env, false);
          out.write(_jsp_string8, 0, _jsp_string8.length);
          _caucho_expr_7.print(out, _jsp_env, false);
          out.write(_jsp_string9, 0, _jsp_string9.length);
          if (_jsp_StringTag_1 == null) {
            _jsp_StringTag_1 = new dms.tag.StringTag();
            _jsp_StringTag_1.setPageContext(pageContext);
            _jsp_StringTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_loop_0);
            _jsp_StringTag_1.setLength(20);
          }

          _jsp_StringTag_1.setValue(_caucho_expr_7.evalString(_jsp_env));
          _jsp_StringTag_1.doStartTag();
          out.write(_jsp_string10, 0, _jsp_string10.length);
          if (_jsp_loop_1 == null)
            _jsp_loop_1 = new com.caucho.jsp.IteratorLoopSupportTag();
          java.lang.Object _jsp_items_11 = _caucho_expr_8.evalObject(_jsp_env);
          java.util.Iterator _jsp_iter_11 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_11);
          _jsp_loop_1.init(0, Integer.MAX_VALUE, 1);
          Object _jsp_status_11 = pageContext.putAttribute("index1", _jsp_loop_1);
          Object _jsp_oldVar_11 = pageContext.getAttribute("obj1");
          while (_jsp_iter_11.hasNext()) {
            Object _jsp_i_11 = _jsp_iter_11.next();
            pageContext.setAttribute("obj1", _jsp_i_11);
            _jsp_loop_1.setCurrent(_jsp_i_11, _jsp_iter_11.hasNext());
            out.write(_jsp_string11, 0, _jsp_string11.length);
            if (_caucho_expr_9.evalBoolean(_jsp_env)) {
              out.write(_jsp_string12, 0, _jsp_string12.length);
              _caucho_expr_10.print(out, _jsp_env, false);
              out.write(_jsp_string13, 0, _jsp_string13.length);
              _caucho_expr_11.print(out, _jsp_env, false);
              out.write(_jsp_string14, 0, _jsp_string14.length);
              _caucho_expr_12.print(out, _jsp_env, false);
              out.write(_jsp_string15, 0, _jsp_string15.length);
              _caucho_expr_2.print(out, _jsp_env, false);
              out.write(_jsp_string16, 0, _jsp_string16.length);
              _caucho_expr_12.print(out, _jsp_env, false);
              out.write(_jsp_string17, 0, _jsp_string17.length);
              _caucho_expr_13.print(out, _jsp_env, false);
              out.write(_jsp_string18, 0, _jsp_string18.length);
              _caucho_expr_6.print(out, _jsp_env, false);
              out.write(_jsp_string19, 0, _jsp_string19.length);
              _caucho_expr_7.print(out, _jsp_env, false);
              out.write(_jsp_string20, 0, _jsp_string20.length);
              _caucho_expr_7.print(out, _jsp_env, false);
              out.write(_jsp_string21, 0, _jsp_string21.length);
              _caucho_expr_14.print(out, _jsp_env, false);
              out.write(_jsp_string22, 0, _jsp_string22.length);
              _caucho_expr_4.print(out, _jsp_env, false);
              out.write(_jsp_string23, 0, _jsp_string23.length);
              _caucho_expr_15.print(out, _jsp_env, false);
              out.write(_jsp_string24, 0, _jsp_string24.length);
              _caucho_expr_6.print(out, _jsp_env, false);
              out.write(_jsp_string25, 0, _jsp_string25.length);
              _caucho_expr_16.print(out, _jsp_env, false);
              out.write(_jsp_string26, 0, _jsp_string26.length);
              _caucho_expr_17.print(out, _jsp_env, false);
              out.write(_jsp_string27, 0, _jsp_string27.length);
              _caucho_expr_18.print(out, _jsp_env, false);
              out.write(_jsp_string28, 0, _jsp_string28.length);
              _caucho_expr_6.print(out, _jsp_env, false);
              out.write(_jsp_string29, 0, _jsp_string29.length);
              _caucho_expr_6.print(out, _jsp_env, false);
              out.write(_jsp_string30, 0, _jsp_string30.length);
            }
            out.write(_jsp_string31, 0, _jsp_string31.length);
          }
          pageContext.pageSetOrRemove("obj1", _jsp_oldVar_11);
          pageContext.removeAttribute("index1");
          out.write(_jsp_string32, 0, _jsp_string32.length);
        }
        pageContext.pageSetOrRemove("obj", _jsp_oldVar_2);
        pageContext.removeAttribute("index");
        out.write(_jsp_string33, 0, _jsp_string33.length);
      }
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_DomainTag_0 != null)
        _jsp_DomainTag_0.release();
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
    manager.addTaglibFunctions(_jsp_functionMap, "mytld", "/tld/MyTld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list!=null&&!empty list}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${index.index*32}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.siteId}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.sellPrice/100}");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.discount/100}");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.id}");
    _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.title}");
    _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.addressList}");
    _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj1.lat!=null&&obj1.lon!=null}");
    _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj1.lat}");
    _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj1.lon}");
    _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj1.viewName}");
    _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.picUrl}");
    _caucho_expr_14 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.orgPrice/100}");
    _caucho_expr_15 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.url}");
    _caucho_expr_16 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.userCount}");
    _caucho_expr_17 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj1.address}");
    _caucho_expr_18 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.endTime1}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("map1.jsp"), -5040647142820010521L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/MyTld.tld"), -2192669327613808265L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.DomainTag.class, -4892645898963761506L));
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.StringTag.class, -2390658830780319460L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;
  private static com.caucho.el.Expr _caucho_expr_14;
  private static com.caucho.el.Expr _caucho_expr_15;
  private static com.caucho.el.Expr _caucho_expr_16;
  private static com.caucho.el.Expr _caucho_expr_17;
  private static com.caucho.el.Expr _caucho_expr_18;

  private final static char []_jsp_string26;
  private final static char []_jsp_string23;
  private final static char []_jsp_string2;
  private final static char []_jsp_string10;
  private final static char []_jsp_string8;
  private final static char []_jsp_string12;
  private final static char []_jsp_string27;
  private final static char []_jsp_string13;
  private final static char []_jsp_string18;
  private final static char []_jsp_string32;
  private final static char []_jsp_string19;
  private final static char []_jsp_string4;
  private final static char []_jsp_string25;
  private final static char []_jsp_string24;
  private final static char []_jsp_string11;
  private final static char []_jsp_string9;
  private final static char []_jsp_string3;
  private final static char []_jsp_string28;
  private final static char []_jsp_string14;
  private final static char []_jsp_string16;
  private final static char []_jsp_string33;
  private final static char []_jsp_string17;
  private final static char []_jsp_string20;
  private final static char []_jsp_string30;
  private final static char []_jsp_string29;
  private final static char []_jsp_string22;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string31;
  private final static char []_jsp_string15;
  private final static char []_jsp_string21;
  private final static char []_jsp_string7;
  private final static char []_jsp_string1;
  static {
    _jsp_string26 = "</em>\u4eba\u8d2d\u4e70\\n                  </div>\\n    </div>    \\n  </div>\\n\\n</div>               \\n  \\n\\n  <div class=\\\"addr\\\">\\n    <div style=\\\"font-size:12px;display:block;\\\">\\n      <strong></strong>".toCharArray();
    _jsp_string23 = "</span>\\n    </div>\\n\\n    <div style=\\\"float:right;clear:both;margin-top:10px;margin-bottom:10px;\\\">\\n      <a class=\\\"view_button\\\" href=\\\"".toCharArray();
    _jsp_string2 = "  \r\n<p><div style=\"float:left;height:32px;margin-right:4px;width:20px;background:url('images/green.png') repeat scroll 0pt -".toCharArray();
    _jsp_string10 = "</a><br></p>\r\n	\r\n".toCharArray();
    _jsp_string8 = "\" onclick=\"alert(11);return false;\" onMouseover=\"ddrivetip('".toCharArray();
    _jsp_string12 = "\r\n<script>\r\n	jQuery(function(){\r\n		var latlon=new google.maps.LatLng(".toCharArray();
    _jsp_string27 = "\\n    </div>\\n    <div style=\\\"height:10px;\\\">\\n    </div>\\n  </div>\\n</div>\\n\";\r\n		addInfoWindow(marker,info);\r\n  	\r\n  	var str = '';\r\nvar myDate = new Date();\r\nvar startTime = myDate.getTime(); \r\nvar endTime = ".toCharArray();
    _jsp_string13 = "/100000,".toCharArray();
    _jsp_string18 = "\\\" class=\\\"small_image\\\" style=\\\"float:left;margin-right:6px;width:91px;height:60px;\\\"/>\\n\\n    <span class=\\\"title\\\">\\n      <a target=\\\"_blank\\\" href=\\\"index.do?method=detail&id=".toCharArray();
    _jsp_string32 = "\r\n\r\n      ".toCharArray();
    _jsp_string19 = "\\\" title=\\\"".toCharArray();
    _jsp_string4 = "\" target=\"_blank\">".toCharArray();
    _jsp_string25 = "\\\" alt=\\\"1283184000000\\\">\\n          \\u3010<em>0</em>\\u5929<em>0</em>\\u5c0f\\u65f6<em>0</em>\\u5206<em>0</em>\\u79d2\\u3011\\n        </span>\\u3011\\n                  </div>\\n      </div>\\n\\n      <div class=\\\"sales_count\\\" style=\\\"float:right;\\\">\\n                        \u5df2\u6709<em>".toCharArray();
    _jsp_string24 = "\\\" rel=\\\"nofollow\\\" target=\\\"_blank\\\"  >\u53bb\u8d2d\u4e70&gt;&gt;</a>\\n    </div>\\n\\n    <div style=\\\"clear:both;overflow:auto;_zoom:1;background-color:#e0e0e0;padding:2px;\\\">\\n      <div style=\\\"float:left;\\\">\\n        <div>\\n                        \\u3010<span class=\\\"time_div timeleft\\\" id=\\\"cd".toCharArray();
    _jsp_string11 = "  \r\n	\r\n".toCharArray();
    _jsp_string9 = "', 250)\"; onMouseout=\"hideddrivetip()\">".toCharArray();
    _jsp_string3 = "px transparent;\" title=\"\"></div>\r\n[<a href=\"index.do?method=site&id=".toCharArray();
    _jsp_string28 = ";\r\nif (startTime>=endTime){\r\n	jQuery('#cd".toCharArray();
    _jsp_string14 = "/100000);\r\n		var title='".toCharArray();
    _jsp_string16 = "))\r\n		var marker=addPoint(latlon,icon,title);\r\n		var info=\"\\n<div class=\\\"map_items\\\" style=\\\"overflow:visible;_zoom:1;\\\">\\n  <div class=\\\"deal_tabs\\\">\\n    \\n        <a href=\\\"#\\\" onclick=\\\"switchToDealTab(this, 12605);return false;\\\" class=\\\"deal_tab current\\\">".toCharArray();
    _jsp_string33 = "\r\n    ".toCharArray();
    _jsp_string17 = "</a>\\n    \\n  </div>\\n  \\n      \\n<div style=\\\"\\\" class=\\\"map_item deal12605\\\" >\\n    <div style=\\\"overflow:visible;margin-top:4px;\\\">\\n    <div class=\\\"overflow:visible;\\\">\\n      <img src=\\\"".toCharArray();
    _jsp_string20 = "\\\">\\n        ".toCharArray();
    _jsp_string30 = "').html(str);\r\n\r\n}});\r\n}\r\nfunction formatNum(n){\r\nreturn n < 10 ? '0' + n : n;\r\n}\r\n\r\n});\r\n</script>\r\n".toCharArray();
    _jsp_string29 = "').html(\"\\n\u5df2\u7ecf\u7ed3\u675f\u3002\\n\");\r\n}else{\r\nnew CD({startTime:startTime, endTime:endTime, callback:function(day, hour, minute, second){\r\nstr = '' + (day != 0 ? day + '\u5929' : '') + formatNum(hour) + '\u65f6' + formatNum(minute) + '\u5206' + (day == 0 ? formatNum(second) + '\u79d2' : '') ;\r\njQuery('#cd".toCharArray();
    _jsp_string22 = ")</span>\\n\\n        <span class=\\\"current\\\" style=\\\"font-size:110%;font-weight:bold;;\\\">\u73b0\u4ef7\uffe5".toCharArray();
    _jsp_string5 = "</a>]\r\n&nbsp;&nbsp;<span class=\"discount\">\u4ec5\u552e".toCharArray();
    _jsp_string6 = "\u5143&nbsp;&nbsp;".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n    ".toCharArray();
    _jsp_string31 = "      \r\n".toCharArray();
    _jsp_string15 = "';\r\n		var icon = new google.maps.MarkerImage(\"images/green.png\",\r\n                                new google.maps.Size(20, 32),\r\n                                new google.maps.Point(0,".toCharArray();
    _jsp_string21 = "\\n      </a>\\n    </span>\\n    </div>\\n\\n    <div class=\\\"price\\\" style=\\\"float:right;margin-top:4px;\\\">\\n        <span class=\\\"original\\\" style=\\\"text-decoration:line-through;margin-right:20px;\\\">(\u539f\u4ef7\uffe5".toCharArray();
    _jsp_string7 = "\u6298 </span>\r\n<br> \r\n<a href=\"index.do?method=detail&id=".toCharArray();
    _jsp_string1 = "\r\n      ".toCharArray();
  }
}
