/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _city__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    response.setCharacterEncoding("UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
		String sql = "select c1.id,c1.city_name,t1.num from city c1,"
				+ "(select c.id,count(t.id) as num from city c,info t WHERE c.id=t.city and t.end_time>? group by c.id) t1 "
				+ "where c1.id=t1.id order by c1.sort_order ";
		java.util.Date now=new java.util.Date ();
		java.util.List list=util.DbUtil.getDao().list(sql, new Object[]{now},-1,-1);
		Number cCity=(Number)request.getAttribute("city");
		
		if (list!=null)
		for (int i=0;i<list.size();i++){
		Object o=list.get(i);
		Object[] objs=(Object[])o;
		Number id=(Number)objs[0];
		String name=(String)objs[1];
		Number num=(Number)objs[2];
		if (cCity!=null&&cCity.intValue()==id.intValue()){
		
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((name));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((num));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      
	  }else{
	  
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((id));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((name));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((num));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      
		}
		if (i%3==0) out.println("<br/>");		
    }
      out.write(_jsp_string8, 0, _jsp_string8.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("city.jsp"), 7619482489500917962L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string8;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string6;
  private final static char []_jsp_string7;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  static {
    _jsp_string5 = "\">".toCharArray();
    _jsp_string8 = "\r\n  </div>".toCharArray();
    _jsp_string3 = ")</span>&nbsp;\r\n		".toCharArray();
    _jsp_string2 = " <span class='count'>(".toCharArray();
    _jsp_string6 = "<span class='count'>(".toCharArray();
    _jsp_string7 = ")</span></a>&nbsp;\r\n		".toCharArray();
    _jsp_string1 = "\r\n		".toCharArray();
    _jsp_string0 = "\r\n  <!--div class=\"city_list\" id=\"city_list\" style=\"display: none;\" onmouseover=\"this.style.display='block';\"  onmouseout=\"this.style.display='none';\"-->\r\n  <div>\r\n  	".toCharArray();
    _jsp_string4 = "\r\n	  <a href=\"index.do?method=list&city=".toCharArray();
  }
}
