/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _newcomment__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_caucho_expr_0.evalBoolean(_jsp_env)) {
        out.write(_jsp_string1, 0, _jsp_string1.length);
        if (_jsp_loop_0 == null)
          _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
        java.lang.Object _jsp_items_1 = _caucho_expr_1.evalObject(_jsp_env);
        java.util.Iterator _jsp_iter_1 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_1);
        _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
        Object _jsp_status_1 = pageContext.putAttribute("index1", _jsp_loop_0);
        Object _jsp_oldVar_1 = pageContext.getAttribute("obj1");
        while (_jsp_iter_1.hasNext()) {
          Object _jsp_i_1 = _jsp_iter_1.next();
          pageContext.setAttribute("obj1", _jsp_i_1);
          _jsp_loop_0.setCurrent(_jsp_i_1, _jsp_iter_1.hasNext());
          out.write(_jsp_string2, 0, _jsp_string2.length);
          _caucho_expr_2.print(out, _jsp_env, false);
          out.write(_jsp_string3, 0, _jsp_string3.length);
          _caucho_expr_3.print(out, _jsp_env, false);
          out.write(_jsp_string4, 0, _jsp_string4.length);
          _caucho_expr_4.print(out, _jsp_env, false);
          out.write(_jsp_string5, 0, _jsp_string5.length);
          _caucho_expr_5.print(out, _jsp_env, false);
          out.write(_jsp_string6, 0, _jsp_string6.length);
          _caucho_expr_4.print(out, _jsp_env, false);
          out.write(_jsp_string7, 0, _jsp_string7.length);
          _caucho_expr_3.print(out, _jsp_env, false);
          out.write(_jsp_string4, 0, _jsp_string4.length);
          _caucho_expr_6.print(out, _jsp_env, false);
          out.write(_jsp_string6, 0, _jsp_string6.length);
          _caucho_expr_6.print(out, _jsp_env, false);
          out.write(_jsp_string8, 0, _jsp_string8.length);
          _caucho_expr_6.print(out, _jsp_env, false);
          out.write(_jsp_string9, 0, _jsp_string9.length);
        }
        pageContext.pageSetOrRemove("obj1", _jsp_oldVar_1);
        pageContext.removeAttribute("index1");
        out.write(_jsp_string10, 0, _jsp_string10.length);
      }
      out.write(_jsp_string11, 0, _jsp_string11.length);
      if (_caucho_expr_7.evalBoolean(_jsp_env)) {
        out.write(_jsp_string1, 0, _jsp_string1.length);
        if (_jsp_loop_0 == null)
          _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
        java.lang.Object _jsp_items_2 = _caucho_expr_8.evalObject(_jsp_env);
        java.util.Iterator _jsp_iter_2 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_2);
        _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
        Object _jsp_status_2 = pageContext.putAttribute("index2", _jsp_loop_0);
        Object _jsp_oldVar_2 = pageContext.getAttribute("obj2");
        while (_jsp_iter_2.hasNext()) {
          Object _jsp_i_2 = _jsp_iter_2.next();
          pageContext.setAttribute("obj2", _jsp_i_2);
          _jsp_loop_0.setCurrent(_jsp_i_2, _jsp_iter_2.hasNext());
          out.write(_jsp_string2, 0, _jsp_string2.length);
          _caucho_expr_9.print(out, _jsp_env, false);
          out.write(_jsp_string12, 0, _jsp_string12.length);
          _caucho_expr_10.print(out, _jsp_env, false);
          out.write(_jsp_string4, 0, _jsp_string4.length);
          _caucho_expr_11.print(out, _jsp_env, false);
          out.write(_jsp_string13, 0, _jsp_string13.length);
          _caucho_expr_12.print(out, _jsp_env, false);
          out.write(_jsp_string6, 0, _jsp_string6.length);
          _caucho_expr_11.print(out, _jsp_env, false);
          out.write(_jsp_string14, 0, _jsp_string14.length);
          _caucho_expr_10.print(out, _jsp_env, false);
          out.write(_jsp_string4, 0, _jsp_string4.length);
          _caucho_expr_13.print(out, _jsp_env, false);
          out.write(_jsp_string6, 0, _jsp_string6.length);
          _caucho_expr_13.print(out, _jsp_env, false);
          out.write(_jsp_string8, 0, _jsp_string8.length);
          _caucho_expr_13.print(out, _jsp_env, false);
          out.write(_jsp_string15, 0, _jsp_string15.length);
        }
        pageContext.pageSetOrRemove("obj2", _jsp_oldVar_2);
        pageContext.removeAttribute("index2");
        out.write(_jsp_string10, 0, _jsp_string10.length);
      }
      out.write(_jsp_string16, 0, _jsp_string16.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
    manager.addTaglibFunctions(_jsp_functionMap, "mytld", "/tld/MyTld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list1!=null&&!empty list1}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list1}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${index1.index==0?\"class='no_border'\":\"\"}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj1[0].id}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj1[0].title}");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj1[0].picUrl}");
    _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj1[1].content}");
    _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list2!=null&&!empty list2}");
    _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list2}");
    _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${index2.index==0?\"class='no_border'\":\"\"}");
    _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj2[0].id}");
    _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj2[0].siteName}");
    _caucho_expr_12 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj2[0].picUrl}");
    _caucho_expr_13 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj2[1].content}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("newComment.jsp"), -531685339579959825L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;
  private static com.caucho.el.Expr _caucho_expr_12;
  private static com.caucho.el.Expr _caucho_expr_13;

  private final static char []_jsp_string11;
  private final static char []_jsp_string2;
  private final static char []_jsp_string14;
  private final static char []_jsp_string0;
  private final static char []_jsp_string15;
  private final static char []_jsp_string13;
  private final static char []_jsp_string3;
  private final static char []_jsp_string8;
  private final static char []_jsp_string16;
  private final static char []_jsp_string5;
  private final static char []_jsp_string9;
  private final static char []_jsp_string7;
  private final static char []_jsp_string6;
  private final static char []_jsp_string10;
  private final static char []_jsp_string12;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  static {
    _jsp_string11 = "\r\n              </ul>\r\n    \r\n    \r\n      <ul class=\"deal_ads comment_ads\" id=\"latest_site_comments\" style=\"display:none\">\r\n        \r\n      ".toCharArray();
    _jsp_string2 = "  \r\n            <li ".toCharArray();
    _jsp_string14 = "\"/>\r\n  </a>\r\n</div>\r\n<div class=\"info\" >\r\n  <a href=\"index.do?method=site&id=".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<div class=\"line_tabs\">\r\n    <a href=\"javascript:void(0)\" id=\"latest_deal_comments_button\" class=\"tab_radius on\">\u6700\u65b0\u56e2\u8d2d\u8bc4\u8bba</a>\r\n    <a href=\"javascript:void(0)\" id=\"latest_site_comments_button\" class=\"tab_radius\">\u6700\u65b0\u7f51\u7ad9\u8bc4\u8bba</a>\r\n  </div>\r\n  <div class=\"mod radius_bottom\" >\r\n\r\n    \r\n      <ul class=\"deal_ads comment_ads on\" id=\"latest_deal_comments\">\r\n        \r\n      ".toCharArray();
    _jsp_string15 = "</a>\r\n</div>\r\n</li>\r\n".toCharArray();
    _jsp_string13 = "\" target=\"_blank\">\r\n    <img class=\"ad_image\" src=\"".toCharArray();
    _jsp_string3 = ">\r\n<div class=\"image\">\r\n  <a href=\"index.do?method=detail&id=".toCharArray();
    _jsp_string8 = "\" target=\"_blank\">".toCharArray();
    _jsp_string16 = " \r\n              </ul>\r\n      </div>\r\n  <script type=\"text/javascript\">\r\n    jQuery(\"#latest_deal_comments_button\").click(function(){\r\n      jQuery('#latest_deal_comments').show();\r\n      jQuery('#latest_site_comments').hide();\r\n      jQuery('#latest_deal_comments_button').addClass('on');\r\n      jQuery('#latest_site_comments_button').removeClass('on');\r\n    });\r\n    jQuery(\"#latest_site_comments_button\").click(function(){\r\n      jQuery('#latest_deal_comments').hide();\r\n      jQuery('#latest_site_comments').show();\r\n      jQuery('#latest_deal_comments_button').removeClass('on');\r\n      jQuery('#latest_site_comments_button').addClass('on');\r\n    });\r\n  </script>\r\n".toCharArray();
    _jsp_string5 = "\" target=\"_blank\"><img src=\"".toCharArray();
    _jsp_string9 = "</a>\r\n</div>\r\n\r\n          </li>\r\n             ".toCharArray();
    _jsp_string7 = "\" class=\"ad_image\"></a>\r\n</div>\r\n<div class=\"info\" >\r\n  <a href=\"index.do?method=detail&id=".toCharArray();
    _jsp_string6 = "\" alt=\"".toCharArray();
    _jsp_string10 = "\r\n".toCharArray();
    _jsp_string12 = ">\r\n            \r\n<div class=\"image\">\r\n  <a href=\"index.do?method=site&id=".toCharArray();
    _jsp_string1 = "\r\n      ".toCharArray();
    _jsp_string4 = "\" title=\"".toCharArray();
  }
}
