/*
 * JSP generated by Resin-3.1.8 (built Mon, 17 Nov 2008 12:15:21 PST)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _service__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    dms.tag.CityTag _jsp_CityTag_0 = null;
    com.caucho.jsp.IteratorLoopSupportTag _jsp_loop_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
   if (request.getParameter("sCity")!=null){
   try{
		Long sc=Long.parseLong(request.getParameter("city"));   
		session.setAttribute("SESSION_CITY",sc);
   }catch(Exception e){}
   }
   
   if (session.getAttribute("SESSION_CITY")!=null){
   	
   }else{
   		session.setAttribute("SESSION_CITY",2l);	
   }
   
   request.setAttribute("SESSION_CITY",session.getAttribute("SESSION_CITY"));
   
      out.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_CityTag_0 == null) {
        _jsp_CityTag_0 = new dms.tag.CityTag();
        _jsp_CityTag_0.setPageContext(pageContext);
        _jsp_CityTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_CityTag_0.setCityId(new java.lang.Long(_caucho_expr_0.evalLong(_jsp_env)));
      _jsp_CityTag_0.doStartTag();
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
		String sql = "select c1.id,c1.city_name,t1.num from city c1,"
				+ "(select c.id,count(t.id) as num from city c,info t WHERE c.id=t.city and t.end_time>now() group by c.id) t1 "
				+ "where c1.id=t1.id order by c1.sort_order ";
		java.util.Date now=new java.util.Date ();
		java.util.List list=util.DbUtil.getDao().list(sql, null,-1,-1);

			int city=2;

			try{
				city=Integer.parseInt(request.getParameter("city"));
			}catch(Exception e){
				try{
					city=Integer.parseInt((String)request.getSession().getAttribute("SESSION_CITY"));
				}catch(Exception e1){
					city=2;
				}
			}

		
		if (list!=null)
		for (int i=0;i<list.size();i++){
		Object o=list.get(i);
		Object[] objs=(Object[])o;
		Number id=(Number)objs[0];
		String name=(String)objs[1];
		Number num=(Number)objs[2];
		if (city==id.intValue()){
		
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((name));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((num));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      
	  }else{
	  
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((id));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((name));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((num));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      
		}
		if (i%5==4) out.println("<br/>");		
    }
      out.write(_jsp_string10, 0, _jsp_string10.length);
      
	if (session.getAttribute("SESSION_USER")==null){
	
      out.write(_jsp_string11, 0, _jsp_string11.length);
      }else{
      out.write(_jsp_string12, 0, _jsp_string12.length);
      }
      out.write(_jsp_string13, 0, _jsp_string13.length);
      
	if (session.getAttribute("SESSION_USER")!=null){
	
      out.write(_jsp_string14, 0, _jsp_string14.length);
      }
      out.write(_jsp_string15, 0, _jsp_string15.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print(("mapView".equals(request.getParameter("method"))?"mapView":"list"));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      if (_caucho_expr_1.evalBoolean(_jsp_env)) {
        out.write(_jsp_string18, 0, _jsp_string18.length);
        if (_jsp_loop_0 == null)
          _jsp_loop_0 = new com.caucho.jsp.IteratorLoopSupportTag();
        java.lang.Object _jsp_items_5 = _caucho_expr_2.evalObject(_jsp_env);
        java.util.Iterator _jsp_iter_5 = com.caucho.jstl.rt.CoreForEachTag.getIterator(_jsp_items_5);
        _jsp_loop_0.init(0, Integer.MAX_VALUE, 1);
        Object _jsp_status_5 = pageContext.putAttribute("index", _jsp_loop_0);
        Object _jsp_oldVar_5 = pageContext.getAttribute("obj");
        while (_jsp_iter_5.hasNext()) {
          Object _jsp_i_5 = _jsp_iter_5.next();
          pageContext.setAttribute("obj", _jsp_i_5);
          _jsp_loop_0.setCurrent(_jsp_i_5, _jsp_iter_5.hasNext());
          out.write(_jsp_string19, 0, _jsp_string19.length);
          _caucho_expr_3.print(out, _jsp_env, false);
          out.write(_jsp_string20, 0, _jsp_string20.length);
          _caucho_expr_4.print(out, _jsp_env, false);
          out.write(_jsp_string21, 0, _jsp_string21.length);
        }
        pageContext.pageSetOrRemove("obj", _jsp_oldVar_5);
        pageContext.removeAttribute("index");
        out.write(_jsp_string18, 0, _jsp_string18.length);
      }
      out.write(_jsp_string22, 0, _jsp_string22.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_CityTag_0 != null)
        _jsp_CityTag_0.release();
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 1886798272571451039L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jstl/core");
    manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jstl/fmt");
    manager.addTaglibFunctions(_jsp_functionMap, "mytld", "/tld/MyTld");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${SESSION_CITY}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list!=null&&!empty list}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${list}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.pic}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${obj.remark}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("service.jsp"), -6002906537940328431L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("header.jsp"), 5870888889786724232L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("city.jsp"), 5280727461662574296L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("bottom.jsp"), 4734239649724377095L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/MyTld.tld"), -2192669327613808265L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(dms.tag.CityTag.class, -5625564777567069442L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;

  private final static char []_jsp_string20;
  private final static char []_jsp_string7;
  private final static char []_jsp_string18;
  private final static char []_jsp_string12;
  private final static char []_jsp_string15;
  private final static char []_jsp_string0;
  private final static char []_jsp_string19;
  private final static char []_jsp_string5;
  private final static char []_jsp_string22;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string13;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string14;
  private final static char []_jsp_string17;
  private final static char []_jsp_string11;
  private final static char []_jsp_string9;
  private final static char []_jsp_string3;
  private final static char []_jsp_string10;
  private final static char []_jsp_string21;
  private final static char []_jsp_string6;
  private final static char []_jsp_string16;
  static {
    _jsp_string20 = "\"/><td>\r\n  <td>".toCharArray();
    _jsp_string7 = "\">".toCharArray();
    _jsp_string18 = "\r\n  ".toCharArray();
    _jsp_string12 = "\r\n	<a href=\"/home.jsp\">\u6211\u7684\u56e2\u7ed3\u5ba2</a>\r\n	".toCharArray();
    _jsp_string15 = "\r\n	</div>\r\n  <div class=\"top_right\"></div> \r\n  </td>\r\n  </tr>\r\n  <tr>\r\n   <td colspan=\"3\" valign=\"bottom\" align=\"center\">\r\n   <table cellSpacing=0 cellPadding=0 width=\"600\" border=0 align=\"center\">\r\n  <tr>\r\n  <td width=\"171\" height=\"29\" class=\"Nav\">\r\n    <a href=\"index.do?method=list\">\u4eca\u65e5\u56e2\u8d2d</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"index.do?method=city&id=".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n<meta name=\"description\" content=\" \">\r\n<meta name=\"keywords\" content=\" \">\r\n<title> </title>\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"css/tuan.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"css/front_new.css\" />\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"style/pageEffect.css\" />\r\n<script type=\"text/javascript\" src=\"js/jquery-1.4.2g.js\"></script>\r\n<script type=\"text/javascript\" src=\"js/util.js\"></script>\r\n<script type=\"text/javascript\" src=\"js/pageEffect.js\"></script>\r\n<script src=\"js/formtools.js\"></script>\r\n<script src=\"js/c.js\"></script>\r\n<script>\r\n	jQuery(function(){\r\n });\r\n\r\n \r\n</script>\r\n\r\n\r\n</head>\r\n<body>\r\n\r\n<script src=\"/js/h.js\"></script>\r\n<table cellSpacing=0 cellPadding=2 width=\"98%\" border=0 align=\"center\">\r\n  <tr>\r\n  <td width=\"89\" rowspan=\"2\"><img src=\"image/logo.jpg\" width=\"202\" height=\"96\"></td>\r\n   <td width=\"100\">\r\n   ".toCharArray();
    _jsp_string19 = "\r\n  <tr> \r\n  <td width=\"80\"><img src=\"".toCharArray();
    _jsp_string5 = ")</span>&nbsp;\r\n		".toCharArray();
    _jsp_string22 = "\r\n  \r\n  </table>\r\n  <br>\r\n  \r\n</div>\r\n\r\n\r\n<div class=\"clean\"></div>\r\n<div style=\"magin:auto; width:96%; text-align:center; height:100px; padding-top:40px;\">\r\n<a href=\"\" target=\"_blank\">\u5173\u4e8e\u6211\u4eec</a> | <a href=\"\" target=\"_blank\">\u5e7f\u544a\u5408\u4f5c</a> | <a href=\"\" target=\"_blank\">\u8054\u7cfb\u6211\u4eec</a> | <a href=\"complain.do?method=list\">\u7528\u6237\u6295\u8bc9</a>| <a href=\"index.do?method=service\">\u4fdd\u969c\u670d\u52a1</a><p>\r\nCopyright &copy 2007-2010 Magickylin.com&nbsp;&nbsp;			\r\n			<a href=\"http://www.miibeian.gov.cn/\" target=\"_blank\">\u4eacICP\u8bc1070743</a></p>\r\n</div>\r\n\r\n</body>\r\n</html>".toCharArray();
    _jsp_string1 = "\r\n   	\r\n  <span class=\"cur_city\">".toCharArray();
    _jsp_string2 = "</span>&nbsp;&nbsp;<span class=\"more_city\"><a href=\"javascript:void(0)\" onmouseover=\"jQuery('#city_list').show();\"  onmouseout=\"jQuery('#city_list').hide();\">\u5207\u6362\u57ce\u5e02</a>\r\n  </span>\r\n<div class=\"city_list\" id=\"city_list\" style=\"display: none;\" onmouseover=\"this.style.display='block';\"  onmouseout=\"this.style.display='none';\">\r\n  	".toCharArray();
    _jsp_string13 = "\r\n	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\" onclick=\"setHomepage();return false;\">\u8bbe\u4e3a\u9996\u9875</a>&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"#\" onclick=\"addCookie();return false;\">\u6536\u85cf\u7ad9\u70b9</a>\r\n		".toCharArray();
    _jsp_string4 = " <span class='count'>(".toCharArray();
    _jsp_string8 = "<span class='count'>(".toCharArray();
    _jsp_string14 = "\r\n	|&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"logout.jsp\">\u9000\u51fa</a>\r\n	".toCharArray();
    _jsp_string17 = "\" method=\"post\" name=\"searchForm\" id=\"searchForm\">\r\n   	<input type=\"hidden\" name=\"pd\" />\r\n   	<input type=\"hidden\" name=\"dd\" />\r\n   	<input type=\"hidden\" name=\"sort\" />\r\n   	<input type=\"hidden\" name=\"sortType\" />\r\n   	<input type=\"hidden\" name=\"type\"/>\r\n   	<input type=\"hidden\" name=\"group\"/>\r\n            <strong>\u56e2\u8d2d\u6d3b\u52a8</strong> <input type=\"text\" class=\"keyword ac_input\" size=\"60\" value=\"\" name=\"key\" id=\"key\"  style=\"color:#999;\" autocomplete=\"off\">\r\n			<select name=\"category\" id=\"category\"><option value=\"-1\">\u6240\u6709\u56e2\u8d2d</option><option value=\"0\">\u4f11\u95f2\u5a31\u4e50</option><option value=\"1\">\u7f8e\u5bb9\u5065\u5eb7</option><option value=\"2\">\u9910\u996e\u7f8e\u98df</option><option value=\"3\">\u7cbe\u54c1\u56e2\u8d2d</option></select>\r\n           <input type=\"button\" class=\"button\" value=\"\u641c\u7d22\"  name=\"button\" id=\"button\" onclick=\"submitForm();\" />\r\n   	</form>    \r\n  </div>\r\n  <div class=\"search_right\"></div> \r\n<div class=\"clean\"></div>\r\n\r\n<div id=\"main\">\r\n<br>\r\n  \r\n  <table cellSpacing=0 cellPadding=2 width=\"600\" border=0 align=\"center\">\r\n	".toCharArray();
    _jsp_string11 = "\r\n	<a href=\"/login.jsp\">\u767b\u5f55</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"/regist.jsp\">\u6ce8\u518c</a>\r\n	".toCharArray();
    _jsp_string9 = ")</span></a>&nbsp;\r\n		".toCharArray();
    _jsp_string3 = "\r\n		".toCharArray();
    _jsp_string10 = "\r\n  </div>\r\n  </td>\r\n  <td width=\"260\"></td>\r\n  <td>\r\n<div class=\"top_left\"></div>\r\n<div class=\"top_middle\">\r\n	".toCharArray();
    _jsp_string21 = "</td>\r\n  </tr>\r\n\r\n  ".toCharArray();
    _jsp_string6 = "\r\n	  <a href=\"index.do?method=list&city=".toCharArray();
    _jsp_string16 = "\">\u56e2\u8d2d\u5927\u5168</a>\r\n  </td>\r\n  <td class=\"Navmap\">\r\n <a href=\"index.do?method=mapView\">\u56e2\u8d2d\u5730\u56fe</a>\r\n   </td>\r\n   <td width=\"200\"></td>\r\n   </tr>\r\n   </table>\r\n  </td>\r\n</tr>\r\n</table>\r\n<div class=\"search_left\"></div>\r\n  <div class=\"search_middle\">\r\n   <form action=\"index.do?method=".toCharArray();
  }
}
